name: Production Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: production-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Cloudflare Workers production
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Build
        shell: bash
        run: |
          pnpm run build

      - name: Deploy production
        shell: bash
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          pnpm run deploy
